export const listData = [
    {
        id: 1,
        title: "Luxurious Modern House",
        image: "https://picsum.photos/200/300",
        bedrooms: 5,
        bathrooms: 3,
        price: 10000,
        address: "123 Main St, Anytown, USA",
        latitude: 37.7749,
        longitude: -122.4194,
        sqft: 5000,
        propertyType: "House",
        yearBuilt: 2015,
        parking: 2,
        furnished: "Fully Furnished",
        heatingCooling: "Central Air & Heating",
        amenities: ["Swimming Pool", "Gym", "Smart Home Features"],
        nearbyLandmarks: ["Central Park", "Downtown Mall"],
        availabilityStatus: "For Sale",
        description: "A luxurious modern house with spacious rooms and state-of-the-art amenities."
    },
    {
        id: 2,
        title: "Cozy Cottage in the Woods",
        image: "https://picsum.photos/200/300",
        bedrooms: 3,
        bathrooms: 2,
        price: 8000,
        address: "456 Oak St, Forestville, USA",
        latitude: 40.7128,
        longitude: -74.0060,
        sqft: 3000,
        propertyType: "Cottage",
        yearBuilt: 2008,
        parking: 1,
        furnished: "Partially Furnished",
        heatingCooling: "Fireplace & Radiant Heating",
        amenities: ["Garden", "Fireplace", "Wooden Deck"],
        nearbyLandmarks: ["National Park", "Lakeview Trail"],
        availabilityStatus: "For Rent",
        description: "A cozy retreat surrounded by nature, perfect for peaceful living."
    },
    {
        id: 3,
        title: "Modern Loft in the City",
        image: "https://picsum.photos/200/300",
        bedrooms: 2,
        bathrooms: 1,
        price: 6000,
        address: "789 Elm St, Cityville, USA",
        latitude: 34.0522,
        longitude: -118.2437,
        sqft: 2000,
        propertyType: "Loft",
        yearBuilt: 2019,
        parking: 0,
        furnished: "Unfurnished",
        heatingCooling: "HVAC",
        amenities: ["Rooftop Terrace", "Fitness Center"],
        nearbyLandmarks: ["Business District", "City Museum"],
        availabilityStatus: "For Rent",
        description: "A stylish loft with an open floor plan, located in the heart of the city."
    },
    {
        id: 4,
        title: "Beach House Getaway",
        image: "https://picsum.photos/200/300",
        bedrooms: 4,
        bathrooms: 3,
        price: 15000,
        address: "321 Beach Dr, Seaside, USA",
        latitude: 25.7617,
        longitude: -80.1918,
        sqft: 4500,
        propertyType: "Beach House",
        yearBuilt: 2012,
        parking: 3,
        furnished: "Fully Furnished",
        heatingCooling: "Ceiling Fans & AC",
        amenities: ["Private Beach", "Outdoor Shower"],
        nearbyLandmarks: ["Seaside Boardwalk", "Luxury Resort"],
        availabilityStatus: "For Sale",
        description: "A stunning beachside retreat with breathtaking ocean views."
    },
    {
        id: 5,
        title: "Rustic Cabin in the Mountains",
        image: "https://picsum.photos/200/300",
        bedrooms: 2,
        bathrooms: 1,
        price: 4000,
        address: "901 Mountain View Dr, Mountainville, USA",
        latitude: 39.7392,
        longitude: -104.9903,
        sqft: 1500,
        propertyType: "Cabin",
        yearBuilt: 1995,
        parking: 1,
        furnished: "Fully Furnished",
        heatingCooling: "Wood Stove & Electric Heating",
        amenities: ["Hiking Trails", "Large Patio"],
        nearbyLandmarks: ["Mountain Peak", "Fishing Lake"],
        availabilityStatus: "For Rent",
        description: "A charming cabin perfect for a weekend getaway in the mountains."
    },
    {
        id: 6,
        title: "Skyline Penthouse",
        image: "https://picsum.photos/200/300",
        bedrooms: 3,
        bathrooms: 2,
        price: 20000,
        address: "111 Highrise Ave, Metropolis, USA",
        latitude: 41.8781,
        longitude: -87.6298,
        sqft: 3500,
        propertyType: "Penthouse",
        yearBuilt: 2020,
        parking: 2,
        furnished: "Fully Furnished",
        heatingCooling: "HVAC",
        amenities: ["Infinity Pool", "Private Elevator"],
        nearbyLandmarks: ["Financial District", "Sky Tower"],
        availabilityStatus: "For Sale",
        description: "A high-end penthouse with panoramic skyline views and top-tier amenities."
    },
    {
        id: 7,
        title: "Lakefront Retreat",
        image: "https://picsum.photos/200/300",
        bedrooms: 5,
        bathrooms: 4,
        price: 18000,
        address: "222 Lakeview Rd, Lakeside, USA",
        latitude: 47.6062,
        longitude: -122.3321,
        sqft: 5500,
        propertyType: "Villa",
        yearBuilt: 2010,
        parking: 2,
        furnished: "Partially Furnished",
        heatingCooling: "Central Heating",
        amenities: ["Boat Dock", "Outdoor BBQ"],
        nearbyLandmarks: ["Lakeside Park", "Fishing Dock"],
        availabilityStatus: "For Sale",
        description: "A spacious lakefront villa with a private dock and scenic views."
    },
    {
        id: 8,
        title: "Suburban Family Home",
        image: "https://picsum.photos/200/300",
        bedrooms: 4,
        bathrooms: 3,
        price: 12000,
        address: "333 Maple St, Suburbia, USA",
        latitude: 32.7767,
        longitude: -96.7970,
        sqft: 4000,
        propertyType: "Single Family Home",
        yearBuilt: 2005,
        parking: 2,
        furnished: "Unfurnished",
        heatingCooling: "HVAC",
        amenities: ["Backyard", "Two-Car Garage"],
        nearbyLandmarks: ["School", "Shopping Mall"],
        availabilityStatus: "For Sale",
        description: "A family-friendly home with a spacious backyard and a safe neighborhood."
    },
    {
        id: 9,
        title: "Historic Brownstone",
        image: "https://picsum.photos/200/300",
        bedrooms: 3,
        bathrooms: 2,
        price: 9000,
        address: "444 Heritage Blvd, Oldtown, USA",
        latitude: 38.9072,
        longitude: -77.0369,
        sqft: 2800,
        propertyType: "Townhouse",
        yearBuilt: 1925,
        parking: 1,
        furnished: "Partially Furnished",
        heatingCooling: "Radiator Heating",
        amenities: ["Private Courtyard", "Roof Deck"],
        nearbyLandmarks: ["Historic District", "Museum"],
        availabilityStatus: "For Rent",
        description: "A beautifully restored brownstone with classic architecture and modern touches."
    },
    {
        id: 10,
        title: "Desert Oasis Villa",
        image: "https://picsum.photos/200/300",
        bedrooms: 4,
        bathrooms: 3,
        price: 17000,
        address: "555 Sand Dune Ln, Desertville, USA",
        latitude: 33.4484,
        longitude: -112.0740,
        sqft: 5000,
        propertyType: "Villa",
        yearBuilt: 2018,
        parking: 2,
        furnished: "Fully Furnished",
        heatingCooling: "Central Cooling",
        amenities: ["Infinity Pool", "Outdoor Lounge"],
        nearbyLandmarks: ["Desert Safari", "Luxury Resort"],
        availabilityStatus: "For Sale",
        description: "A luxurious desert villa with stunning views and top-notch amenities."
    }
];
