export const listData = [
    {
        id: 1,
        title: "Luxurious Modern House",
        image: "https://picsum.photos/200/300",
        bedrooms: 5,
        bathrooms: 3,
        price: 10000,
        address: "123 Main St, Anytown, USA",
        latitude: 37.7749,
        longitude: -122.4194,
        sqft: 5000,
        propertyType: "House",
        yearBuilt: 2015,
        parking: 2,
        furnished: "Fully Furnished",
        heatingCooling: "Central Air & Heating",
        amenities: ["Swimming Pool", "Gym", "Smart Home Features"],
        nearbyLandmarks: ["Central Park", "Downtown Mall"],
        availabilityStatus: "For Sale",
        description: "A luxurious modern house with spacious rooms and state-of-the-art amenities."
    },
    {
        id: 2,
        title: "Cozy Cottage in the Woods",
        image: "https://picsum.photos/200/300",
        bedrooms: 3,
        bathrooms: 2,
        price: 8000,
        address: "456 Oak St, Forestville, USA",
        latitude: 40.7128,
        longitude: -74.0060,
        sqft: 3000,
        propertyType: "Cottage",
        yearBuilt: 2008,
        parking: 1,
        furnished: "Partially Furnished",
        heatingCooling: "Fireplace & Radiant Heating",
        amenities: ["Garden", "Fireplace", "Wooden Deck"],
        nearbyLandmarks: ["National Park", "Lakeview Trail"],
        availabilityStatus: "For Rent",
        description: "A cozy retreat surrounded by nature, perfect for peaceful living."
    },
    {
        id: 3,
        title: "Modern Loft in the City",
        image: "https://picsum.photos/200/300",
        bedrooms: 2,
        bathrooms: 1,
        price: 6000,
        address: "789 Elm St, Cityville, USA",
        latitude: 34.0522,
        longitude: -118.2437,
        sqft: 2000,
        propertyType: "Loft",
        yearBuilt: 2019,
        parking: 0,
        furnished: "Unfurnished",
        heatingCooling: "HVAC",
        amenities: ["Rooftop Terrace", "Fitness Center"],
        nearbyLandmarks: ["Business District", "City Museum"],
        availabilityStatus: "For Rent",
        description: "A stylish loft with an open floor plan, located in the heart of the city."
    },
    {
        id: 4,
        title: "Beach House Getaway",
        image: "https://picsum.photos/200/300",
        bedrooms: 4,
        bathrooms: 3,
        price: 15000,
        address: "321 Beach Dr, Seaside, USA",
        latitude: 25.7617,
        longitude: -80.1918,
        sqft: 4500,
        propertyType: "Beach House",
        yearBuilt: 2012,
        parking: 3,
        furnished: "Fully Furnished",
        heatingCooling: "Ceiling Fans & AC",
        amenities: ["Private Beach", "Outdoor Shower"],
        nearbyLandmarks: ["Seaside Boardwalk", "Luxury Resort"],
        availabilityStatus: "For Sale",
        description: "A stunning beachside retreat with breathtaking ocean views."
    },
    {
        id: 5,
        title: "Rustic Cabin in the Mountains",
        image: "https://picsum.photos/200/300",
        bedrooms: 2,
        bathrooms: 1,
        price: 4000,
        address: "901 Mountain View Dr, Mountainville, USA",
        latitude: 39.7392,
        longitude: -104.9903,
        sqft: 1500,
        propertyType: "Cabin",
        yearBuilt: 1995,
        parking: 1,
        furnished: "Fully Furnished",
        heatingCooling: "Wood Stove & Electric Heating",
        amenities: ["Hiking Trails", "Large Patio"],
        nearbyLandmarks: ["Mountain Peak", "Fishing Lake"],
        availabilityStatus: "For Rent",
        description: "A charming cabin perfect for a weekend getaway in the mountains."
    },
    {
        id: 6,
        title: "Skyline Penthouse",
        image: "https://picsum.photos/200/300",
        bedrooms: 3,
        bathrooms: 2,
        price: 20000,
        address: "111 Highrise Ave, Metropolis, USA",
        latitude: 41.8781,
        longitude: -87.6298,
        sqft: 3500,
        propertyType: "Penthouse",
        yearBuilt: 2020,
        parking: 2,
        furnished: "Fully Furnished",
        heatingCooling: "HVAC",
        amenities: ["Infinity Pool", "Private Elevator"],
        nearbyLandmarks: ["Financial District", "Sky Tower"],
        availabilityStatus: "For Sale",
        description: "A high-end penthouse with panoramic skyline views and top-tier amenities."
    },
    {
        id: 7,
        title: "Lakefront Retreat",
        image: "https://picsum.photos/200/300",
        bedrooms: 5,
        bathrooms: 4,
        price: 18000,
        address: "222 Lakeview Rd, Lakeside, USA",
        latitude: 47.6062,
        longitude: -122.3321,
        sqft: 5500,
        propertyType: "Villa",
        yearBuilt: 2010,
        parking: 2,
        furnished: "Partially Furnished",
        heatingCooling: "Central Heating",
        amenities: ["Boat Dock", "Outdoor BBQ"],
        nearbyLandmarks: ["Lakeside Park", "Fishing Dock"],
        availabilityStatus: "For Sale",
        description: "A spacious lakefront villa with a private dock and scenic views."
    },
    {
        id: 8,
        title: "Suburban Family Home",
        image: "https://picsum.photos/200/300",
        bedrooms: 4,
        bathrooms: 3,
        price: 12000,
        address: "333 Maple St, Suburbia, USA",
        latitude: 32.7767,
        longitude: -96.7970,
        sqft: 4000,
        propertyType: "Single Family Home",
        yearBuilt: 2005,
        parking: 2,
        furnished: "Unfurnished",
        heatingCooling: "HVAC",
        amenities: ["Backyard", "Two-Car Garage"],
        nearbyLandmarks: ["School", "Shopping Mall"],
        availabilityStatus: "For Sale",
        description: "A family-friendly home with a spacious backyard and a safe neighborhood."
    },
    {
        id: 9,
        title: "Historic Brownstone",
        image: "https://picsum.photos/200/300",
        bedrooms: 3,
        bathrooms: 2,
        price: 9000,
        address: "444 Heritage Blvd, Oldtown, USA",
        latitude: 38.9072,
        longitude: -77.0369,
        sqft: 2800,
        propertyType: "Townhouse",
        yearBuilt: 1925,
        parking: 1,
        furnished: "Partially Furnished",
        heatingCooling: "Radiator Heating",
        amenities: ["Private Courtyard", "Roof Deck"],
        nearbyLandmarks: ["Historic District", "Museum"],
        availabilityStatus: "For Rent",
        description: "A beautifully restored brownstone with classic architecture and modern touches."
    },
    {
        id: 10,
        title: "Desert Oasis Villa",
        image: "https://picsum.photos/200/300",
        bedrooms: 4,
        bathrooms: 3,
        price: 17000,
        address: "555 Sand Dune Ln, Desertville, USA",
        latitude: 33.4484,
        longitude: -112.0740,
        sqft: 5000,
        propertyType: "Villa",
        yearBuilt: 2018,
        parking: 2,
        furnished: "Fully Furnished",
        heatingCooling: "Central Cooling",
        amenities: ["Infinity Pool", "Outdoor Lounge"],
        nearbyLandmarks: ["Desert Safari", "Luxury Resort"],
        availabilityStatus: "For Sale",
        description: "A luxurious desert villa with stunning views and top-notch amenities."
    },
    {
        id: 11,
        title: "Elegant Bungalow",
        image: "https://picsum.photos/200/300",
        bedrooms: 4,
        bathrooms: 3,
        price: 13000,
        address: "10 Marine Drive, Mumbai, India",
        latitude: 18.9440,
        longitude: 72.8238,
        sqft: 3200,
        propertyType: "Bungalow",
        yearBuilt: 2015,
        parking: 2,
        furnished: "Fully Furnished",
        heatingCooling: "Central Air",
        amenities: ["Garden", "Private Pool"],
        nearbyLandmarks: ["Gateway of India", "Nariman Point"],
        availabilityStatus: "For Sale",
        description: "A chic bungalow with a private garden in the heart of Mumbai."
    },
    {
        id: 12,
        title: "Luxury Apartment",
        image: "https://picsum.photos/200/300",
        bedrooms: 3,
        bathrooms: 2,
        price: 11000,
        address: "22 Brigade Road, Bangalore, India",
        latitude: 12.9716,
        longitude: 77.5946,
        sqft: 2500,
        propertyType: "Apartment",
        yearBuilt: 2018,
        parking: 1,
        furnished: "Partially Furnished",
        heatingCooling: "HVAC",
        amenities: ["Gym", "Clubhouse"],
        nearbyLandmarks: ["MG Road", "Lalbagh"],
        availabilityStatus: "For Rent",
        description: "A modern apartment with stunning city views in Bangalore."
    },
    {
        id: 13,
        title: "Heritage Haveli",
        image: "https://picsum.photos/200/300",
        bedrooms: 6,
        bathrooms: 4,
        price: 20000,
        address: "15 City Palace Road, Jaipur, India",
        latitude: 26.9124,
        longitude: 75.7873,
        sqft: 6000,
        propertyType: "Haveli",
        yearBuilt: 1890,
        parking: 3,
        furnished: "Fully Furnished",
        heatingCooling: "Radiant Heating",
        amenities: ["Courtyard", "Terrace"],
        nearbyLandmarks: ["Hawa Mahal", "Amber Fort"],
        availabilityStatus: "For Sale",
        description: "A historic haveli with royal architecture in Jaipur."
    },
    {
        id: 14,
        title: "Beachfront Villa",
        image: "https://picsum.photos/200/300",
        bedrooms: 5,
        bathrooms: 4,
        price: 25000,
        address: "50 Beach Road, Goa, India",
        latitude: 15.2993,
        longitude: 74.1240,
        sqft: 4000,
        propertyType: "Villa",
        yearBuilt: 2020,
        parking: 2,
        furnished: "Fully Furnished",
        heatingCooling: "Central Air",
        amenities: ["Beach Access", "Infinity Pool"],
        nearbyLandmarks: ["Calangute Beach", "Fort Aguada"],
        availabilityStatus: "For Sale",
        description: "A lavish villa with private beach access in Goa."
    },
    {
        id: 15,
        title: "Urban Loft",
        image: "https://picsum.photos/200/300",
        bedrooms: 2,
        bathrooms: 1,
        price: 8000,
        address: "88 Connaught Place, New Delhi, India",
        latitude: 28.6315,
        longitude: 77.2167,
        sqft: 1800,
        propertyType: "Loft",
        yearBuilt: 2019,
        parking: 1,
        furnished: "Unfurnished",
        heatingCooling: "HVAC",
        amenities: ["Rooftop Deck", "Fitness Center"],
        nearbyLandmarks: ["India Gate", "Red Fort"],
        availabilityStatus: "For Rent",
        description: "A trendy loft with modern amenities in New Delhi."
    },
    {
        id: 16,
        title: "Colonial Mansion",
        image: "https://picsum.photos/200/300",
        bedrooms: 7,
        bathrooms: 5,
        price: 30000,
        address: "1 Park Street, Kolkata, India",
        latitude: 22.5726,
        longitude: 88.3639,
        sqft: 7000,
        propertyType: "Mansion",
        yearBuilt: 1920,
        parking: 4,
        furnished: "Partially Furnished",
        heatingCooling: "Central Heating",
        amenities: ["Ballroom", "Library"],
        nearbyLandmarks: ["Victoria Memorial", "Howrah Bridge"],
        availabilityStatus: "For Sale",
        description: "A grand colonial mansion with historical significance in Kolkata."
    },
    {
        id: 17,
        title: "Penthouse Suite",
        image: "https://picsum.photos/200/300",
        bedrooms: 3,
        bathrooms: 3,
        price: 22000,
        address: "12 ECR, Chennai, India",
        latitude: 13.0827,
        longitude: 80.2707,
        sqft: 3500,
        propertyType: "Penthouse",
        yearBuilt: 2021,
        parking: 2,
        furnished: "Fully Furnished",
        heatingCooling: "HVAC",
        amenities: ["Private Elevator", "Jacuzzi"],
        nearbyLandmarks: ["Marina Beach", "Kapaleeshwarar Temple"],
        availabilityStatus: "For Sale",
        description: "A luxurious penthouse with exclusive amenities in Chennai."
    },
    {
        id: 18,
        title: "Countryside Farmhouse",
        image: "https://picsum.photos/200/300",
        bedrooms: 5,
        bathrooms: 3,
        price: 15000,
        address: "25 Green Valley, Pune, India",
        latitude: 18.5204,
        longitude: 73.8567,
        sqft: 5000,
        propertyType: "Farmhouse",
        yearBuilt: 2010,
        parking: 3,
        furnished: "Partially Furnished",
        heatingCooling: "Radiant Heating",
        amenities: ["Stable", "Orchard"],
        nearbyLandmarks: ["Sinhagad Fort", "Aga Khan Palace"],
        availabilityStatus: "For Sale",
        description: "A serene farmhouse surrounded by nature near Pune."
    },
    {
        id: 19,
        title: "Riverside Cottage",
        image: "https://picsum.photos/200/300",
        bedrooms: 3,
        bathrooms: 2,
        price: 10000,
        address: "8 Riverside, Rishikesh, India",
        latitude: 30.0869,
        longitude: 78.2676,
        sqft: 3000,
        propertyType: "Cottage",
        yearBuilt: 2015,
        parking: 1,
        furnished: "Fully Furnished",
        heatingCooling: "Radiant Heating",
        amenities: ["River View", "Fireplace"],
        nearbyLandmarks: ["Laxman Jhula", "Triveni Ghat"],
        availabilityStatus: "For Rent",
        description: "A quaint riverside cottage with stunning views in Rishikesh."
    },
    {
        id: 20,
        title: "Skyline Apartment",
        image: "https://picsum.photos/200/300",
        bedrooms: 2,
        bathrooms: 2,
        price: 9000,
        address: "5 Hi-Tech City, Hyderabad, India",
        latitude: 17.3850,
        longitude: 78.4867,
        sqft: 2200,
        propertyType: "Apartment",
        yearBuilt: 2017,
        parking: 1,
        furnished: "Unfurnished",
        heatingCooling: "Central Air",
        amenities: ["Swimming Pool", "Gym"],
        nearbyLandmarks: ["Charminar", "Hussain Sagar"],
        availabilityStatus: "For Rent",
        description: "A modern apartment with panoramic city views in Hyderabad."
    }

];
